/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ChargingData struct {

	// Univocally identifies the charging control policy data within a PDU session.
	ChgId string `json:"chgId"`

	MeteringMethod *MeteringMethod `json:"meteringMethod,omitempty"`

	// Indicates the offline charging is applicable to the PDU session or PCC rule.
	Offline bool `json:"offline,omitempty"`

	// Indicates the online charging is applicable to the PDU session or PCC rule.
	Online bool `json:"online,omitempty"`

	RatingGroup int32 `json:"ratingGroup,omitempty"`

	ReportingLevel *ReportingLevel `json:"reportingLevel,omitempty"`

	ServiceId int32 `json:"serviceId,omitempty"`

	// Indicates the sponsor identity.
	SponsorId string `json:"sponsorId,omitempty"`

	// Indicates the application service provider identity.
	AppSvcProvId string `json:"appSvcProvId,omitempty"`

	AfChargingIdentifier int32 `json:"afChargingIdentifier,omitempty"`
}
