/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PacketFilterOperation - Possible values are - DELETION: Indicates that the resources reserved for the provided packet filter identifiers are to be deleted and are no longer used by the UE.  - ADDITION: Indicates that the UE requests resources allocated for the provided packet filters. - MODIFICATION: Indicates that the reserved QoS, the filter, the precedence, or any of the fields for the provided packet filter identifiers are being modified. 
type PacketFilterOperation struct {
}
