/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Ambr struct {

	Uplink string `json:"uplink"`

	Downlink string `json:"downlink"`
}
