/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ErrorReport struct {

	Error *ProblemDetails `json:"error,omitempty"`

	// Used to report the PCC rule failure.
	RuleReports []RuleReport `json:"ruleReports,omitempty"`
}
