/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PresenceInfoRm struct {

	PraId string `json:"praId,omitempty"`

	PresenceState *PresenceState `json:"presenceState,omitempty"`

	TrackingAreaList []Tai `json:"trackingAreaList,omitempty"`

	EcgiList []Ecgi `json:"ecgiList,omitempty"`

	NcgiList []Ncgi `json:"ncgiList,omitempty"`

	GlobalRanNodeIdList []GlobalRanNodeId `json:"globalRanNodeIdList,omitempty"`
}
