/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SmPolicyControl struct {

	Context *SmPolicyContextData `json:"context"`

	Policy *SmPolicyDecision `json:"policy"`
}
