/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RouteInformation struct {

	Ipv4Addr string `json:"ipv4Addr,omitempty"`

	Ipv6Addr string `json:"ipv6Addr,omitempty"`

	PortNumber int32 `json:"portNumber"`
}
