/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type QosCharacteristics struct {

	Var5qi int32 `json:"5qi"`

	ResourceType *QosResourceType `json:"resourceType"`

	PriorityLevel int32 `json:"priorityLevel"`

	PacketDelayBudget int32 `json:"packetDelayBudget"`

	PacketErrorRate string `json:"packetErrorRate"`

	AveragingWindow int32 `json:"averagingWindow,omitempty"`

	MaxDataBurstVol int32 `json:"maxDataBurstVol,omitempty"`
}
