/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UeInitiatedResourceRequest struct {

	PackFiltOp *PacketFilterOperation `json:"packFiltOp"`

	PackFiltInfo []PacketFilterInfo `json:"packFiltInfo"`

	ReqQos *RequestedQos `json:"reqQos,omitempty"`
}
