/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UeCampingRep struct {

	AccessType *AccessType `json:"accessType,omitempty"`

	RatType *RatType `json:"ratType,omitempty"`

	ServingNetwork *NetworkId `json:"servingNetwork,omitempty"`

	UserLocationInfo *UserLocation `json:"userLocationInfo,omitempty"`

	UeTimeZone string `json:"ueTimeZone,omitempty"`
}
