/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Ncgi struct {

	PlmnId *PlmnId `json:"plmnId"`

	NrCellId string `json:"nrCellId"`
}
