/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PartialSuccessReport struct {

	// Application error cause specific to this report.
	FailureCause string `json:"failureCause"`

	RuleReports []RuleReport `json:"ruleReports"`

	UeCampingRep *UeCampingRep `json:"ueCampingRep,omitempty"`
}
