/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SubscribedDefaultQos struct {

	Var5qi int32 `json:"5qi"`

	Arp *Arp `json:"arp"`

	PriorityLevel int32 `json:"priorityLevel,omitempty"`
}
