/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SessionRule struct {

	AuthSessAmbr *Ambr `json:"authSessAmbr,omitempty"`

	AuthDefQos *AuthorizedDefaultQos `json:"authDefQos,omitempty"`

	// Univocally identifies the session rule within a PDU session.
	SessRuleId string `json:"sessRuleId"`

	// A reference to UsageMonitoringData policy decision type. It is the umId described in subclause 5.6.2.12.
	RefUmData string `json:"refUmData,omitempty"`

	// A reference to the condition data. It is the condId described in subclause 5.6.2.9.
	RefCondData string `json:"refCondData,omitempty"`
}
