/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AccNetChargingAddress - Describes the network entity within the access network performing charging
type AccNetChargingAddress struct {
}
