/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		"GET",
		"/npcf-smpolicycontrol/v1/",
		Index,
	},

	{
		"SmPoliciesPost",
		strings.ToUpper("Post"),
		"/npcf-smpolicycontrol/v1/sm-policies",
		SmPoliciesPost,
	},

	{
		"SmPoliciesSmPolicyIdDeletePost",
		strings.ToUpper("Post"),
		"/npcf-smpolicycontrol/v1/sm-policies/{smPolicyId}/delete",
		SmPoliciesSmPolicyIdDeletePost,
	},

	{
		"SmPoliciesSmPolicyIdGet",
		strings.ToUpper("Get"),
		"/npcf-smpolicycontrol/v1/sm-policies/{smPolicyId}",
		SmPoliciesSmPolicyIdGet,
	},

	{
		"SmPoliciesSmPolicyIdUpdatePost",
		strings.ToUpper("Post"),
		"/npcf-smpolicycontrol/v1/sm-policies/{smPolicyId}/update",
		SmPoliciesSmPolicyIdUpdatePost,
	},
}
